### PR TITLE
Add Unto subscriptions

### PR DESCRIPTION
**Pull request by wrandall22**
[Reference doc](https://docs.google.com/spreadsheets/d/1b4OfKqLhKZV_CNdJbnJd6eB6RUhIn2g36v-z-oqbmN8/edit?ts=5f29885d#gid=391485216)

### CODE REVIEW

**Comment by j2trumpet** [comment]
I don't have access to the reference document. Is that critical for me to read before approving?

**Comment by wrandall22** [comment]
Relevant portion:
Screen Shot 2020-08-04 at 5 52 26 PM

**Comment by j2trumpet** [comment]
The one thing you might consider changing is the `input` and corresponding `label` are currently sibling elements. It's pretty common to make the `input` a child of its `label`. This allows the user to click anywhere on the `label`'s text and check the `input`'s checkbox. Bigger hit area. This was one of the changes I made to the omni-search's HTML.

`<label><input type="checkbox" /> Label text</label>`

**Comment by wrandall22** [comment]
Currently the whole label is clickable to update the checkbox. Moving the input inside of the label breaks the styling.

**Pull request merged**
